"""M1 spatial schema: communes, parcels, buildings, addresses

Revision ID: 5cfd1a07b1f0
Revises: aebf224488fd
Create Date: 2026-08-30 04:23:20.971498
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

revision: str = "5cfd1a07b1f0"
down_revision: str | None = "aebf224488fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # unaccent() is STABLE, not IMMUTABLE, in stock Postgres — it depends on the
    # default text search configuration. The 2-arg form pins the dictionary
    # explicitly, which removes that dependency and lets us wrap it as
    # IMMUTABLE so it can back a generated column (addresses.street_name_normalized).
    op.execute(
        "CREATE FUNCTION unaccent_immutable(text) RETURNS text AS "
        "$$ SELECT unaccent('unaccent', $1) $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building_natures",
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "communes",
        sa.Column("lau2_code", sa.String(length=4), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("canton", sa.Text(), nullable=True),
        sa.Column("district", sa.Text(), nullable=True),
        sa.Column("circonscription_electorale", sa.Text(), nullable=True),
        sa.Column("arrondissement_judiciaire", sa.Text(), nullable=True),
        sa.Column("surface_m2", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=2169,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("lau2_code"),
    )
    # No explicit spatial index here: geoalchemy2's Geometry(spatial_index=True)
    # (the default) attaches its own DDL event that creates/drops the GiST index
    # whenever the table is created/dropped. An explicit op.create_index for the
    # same index name duplicates it and fails with DuplicateTable — caught by
    # actually running this migration, not anticipated in advance.
    op.create_table(
        "parcel_natures",
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "cadastral_communes",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("admin_commune_code", sa.String(length=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_commune_code"], ["communes.lau2_code"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "buildings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("occupation_code", sa.Integer(), nullable=True),
        sa.Column("cadastral_commune_code", sa.String(length=3), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=2169,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cadastral_commune_code"], ["cadastral_communes.code"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["occupation_code"], ["building_natures.code"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cadastral_sections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cadastral_commune_code", sa.String(length=3), nullable=False),
        sa.Column("section_code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cadastral_commune_code"], ["cadastral_communes.code"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cadastral_commune_code", "section_code"),
    )
    op.create_table(
        "parcels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cadastral_id", sa.String(length=15), nullable=False),
        sa.Column("cadastral_commune_code", sa.String(length=3), nullable=False),
        sa.Column("section_code", sa.String(length=2), nullable=False),
        sa.Column("numero_principal", sa.Integer(), nullable=False),
        sa.Column("numero_secondaire", sa.Integer(), nullable=False),
        sa.Column("lieudit", sa.Text(), nullable=True),
        sa.Column("nature_code", sa.Integer(), nullable=True),
        sa.Column("admin_commune_code", sa.String(length=4), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=2169,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "area_geom_m2",
            sa.Numeric(asdecimal=False),
            sa.Computed("ST_Area(geom)", persisted=True),
            nullable=False,
        ),
        sa.Column("area_declared_m2", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_commune_code"], ["communes.lau2_code"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["cadastral_commune_code"], ["cadastral_communes.code"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["nature_code"], ["parcel_natures.code"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cadastral_commune_code", "section_code", "numero_principal", "numero_secondaire"
        ),
        sa.UniqueConstraint("cadastral_id"),
    )
    op.create_index("ix_parcels_admin_commune", "parcels", ["admin_commune_code"], unique=False)
    op.create_index(
        "ix_parcels_cadastral_ref",
        "parcels",
        ["cadastral_commune_code", "section_code", "numero_principal"],
        unique=False,
    )
    op.create_table(
        "addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id_geoportail", sa.Text(), nullable=False),
        sa.Column("caclr_rue_id", sa.Integer(), nullable=True),
        sa.Column("caclr_bat_id", sa.Integer(), nullable=True),
        sa.Column("street_name", sa.Text(), nullable=False),
        sa.Column(
            "street_name_normalized",
            sa.Text(),
            sa.Computed("unaccent_immutable(lower(street_name))", persisted=True),
            nullable=False,
        ),
        sa.Column("house_number", sa.String(length=10), nullable=False),
        sa.Column("locality", sa.Text(), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("admin_commune_code", sa.String(length=4), nullable=True),
        sa.Column("parcel_id", sa.Uuid(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=2169,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_commune_code"], ["communes.lau2_code"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["parcel_id"], ["parcels.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id_geoportail"),
    )
    op.create_index("ix_addresses_admin_commune", "addresses", ["admin_commune_code"], unique=False)
    op.create_table(
        "parcel_buildings",
        sa.Column("parcel_id", sa.Uuid(), nullable=False),
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("overlap_m2", sa.Numeric(asdecimal=False), nullable=False),
        sa.ForeignKeyConstraint(["building_id"], ["buildings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parcel_id"], ["parcels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parcel_id", "building_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parcel_buildings")
    op.drop_index("ix_addresses_admin_commune", table_name="addresses")
    op.drop_table("addresses")
    op.drop_index("ix_parcels_cadastral_ref", table_name="parcels")
    op.drop_index("ix_parcels_admin_commune", table_name="parcels")
    op.drop_table("parcels")
    op.drop_table("cadastral_sections")
    op.drop_table("buildings")
    op.drop_table("cadastral_communes")
    op.drop_table("parcel_natures")
    op.drop_table("communes")
    op.drop_table("building_natures")
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION unaccent_immutable(text)")
