"""pap_nq_zones table for M2

Revision ID: b4054cb7ca57
Revises: 3a2c10aeb564
Create Date: 2026-09-03 20:42:23.186691
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

revision: str = "b4054cb7ca57"
down_revision: str | None = "3a2c10aeb564"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pap_nq_zones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_commune_code", sa.String(length=4), nullable=False),
        sa.Column("denomination", sa.Text(), nullable=True),
        sa.Column("genre", sa.Text(), nullable=True),
        sa.Column("cos_min", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("cos_max", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("cus_min", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("cus_max", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("css_max", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("dl_min", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("dl_max", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("written_document_id", sa.Uuid(), nullable=True),
        sa.Column("schema_directeur_filename", sa.Text(), nullable=True),
        sa.Column("schema_directeur_graphic_filename", sa.Text(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=2169,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_commune_code"], ["communes.lau2_code"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["written_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pap_nq_zones_admin_commune", "pap_nq_zones", ["admin_commune_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pap_nq_zones_admin_commune", table_name="pap_nq_zones")
    op.drop_table("pap_nq_zones")
    # ### end Alembic commands ###
