"""add trigram GIN index on addresses.street_name_normalized

Revision ID: c22a02007eae
Revises: febbc3ec00f2
Create Date: 2026-08-31 19:27:24.342544
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "c22a02007eae"
down_revision: str | None = "febbc3ec00f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_addresses_street_name_trgm",
        "addresses",
        ["street_name_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"street_name_normalized": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_addresses_street_name_trgm",
        table_name="addresses",
        postgresql_using="gin",
        postgresql_ops={"street_name_normalized": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
