"""widen section_code to 3 chars (Luxembourg City sub-sections)

Revision ID: febbc3ec00f2
Revises: 5cfd1a07b1f0
Create Date: 2026-08-30 04:43:53.683299
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "febbc3ec00f2"
down_revision: str | None = "5cfd1a07b1f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cadastral_sections",
        "section_code",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.String(length=3),
        existing_nullable=False,
    )
    op.alter_column(
        "parcels",
        "section_code",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.String(length=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parcels",
        "section_code",
        existing_type=sa.String(length=3),
        type_=sa.VARCHAR(length=2),
        existing_nullable=False,
    )
    op.alter_column(
        "cadastral_sections",
        "section_code",
        existing_type=sa.String(length=3),
        type_=sa.VARCHAR(length=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
